### ISSUE TITLE
git-flow-format links to GitHub mirror, not the source repo

### ISSUE THREAD

**Issue by renyard** [divad12/vim-awesome#66]
The listing for my plugin, [git-flow-format](http://vimawesome.com/plugin/git-flow-format) is linking to the vim-scripts mirror, rather than my original repo. The installation instructions are also pointing to the mirror.

The mirror is currently out of date, compared to the original, and is missing a couple of bug fixes.

Mirror: https://github.com/vim-scripts/git-flow-format
Original: https://github.com/renyard/vim-git-flow-format

**Comment by renyard** [comment]
Looks like the mirror has now picked up the latest version, but the description on vim-awesome is still out of date with the current functionality.

**Comment by divad12** [comment]
Hi Renyard,

I'll need to look into the automated scraper and aggregator to determine why it's deciding to point to the vim-scripts mirror over the original repo. There's a bunch of heuristics that try to determine which is the more "authoritative" GitHub repo — it's clearly failing in this case. (It could be that more of the dotfiles repos we're scraping have vim config files that point to the vim-scripts mirror rather than the original.)

Keeping this open so I can investigate when I have time. Have a busy weekend and will be gone on vacation for a week soon, so no guarantees this will be soon.

Thanks for bringing this up!

**Comment by renyard** [comment]
Thanks David

I suspect that you're right about more dotfiles pointing at the mirror. Let
me know if there's any more info I can provide.

The mirror is listing me as the author of the commits. Maybe this could be
compared against the GitHub and vim.org accounts, if it's not already? Are
the heuristics in tools/scrape/build_github_index.py? I may have some time
next week and I'd be happy to take a look.

Thanks

**Comment by divad12** [comment]
I think where we decide which GitHub repo to show is here:

https://github.com/divad12/vim-awesome/blob/c02cd9812014cbe3cc724be3483efab4545f29a6/db/plugins.py#L288

It looks like it takes # of GitHub stars into account.

Theres's more to it (like we need to have associated the vim-scripts mirror with your original repo in the scraping step), but I seem to have forgotten most of the details myself. :)

I wrote a really dry report on how all the data scraping works last year back when I did this for a school project: https://www.dropbox.com/s/24owxihtek7vau9/report.pdf?dl=0

It's really dry and a boring read, my apologies. Don't feel like you need to read that, but I'll probably need to read it for a refresher.

**Comment by captbaritone** [comment]
I think this has resolved itself: http://vimawesome.com/plugin/git-flow-format

If you have any followup questions, we can always reopen.
